#!/usr/bin/env bash

fifoname="/milk/shm/vispyr_fpsCTRL.fifo"

echo "setval DMch2disp-00.astrogrid.nbframe 1" >> ${fifoname}
echo "setval DMch2disp-00.astrogrid.delay 0" >> ${fifoname}
echo "setval DMch2disp-00.astrogrid.mult 0.100" >> ${fifoname}
echo "setval DMch2disp-00.astrogrid.mode ON" >> ${fifoname}


# log information
dologext "ASTROGID ON  amp = 0.100 um  speed = 1x  15.5 l/d diag" &


scxkw-setter set X_GRDST XYdiag 0
scxkw-setter set X_GRDAMP 0.100
scxkw-setter set X_GRDSEP 15.5
scxkw-setter set X_GRDMOD 2000
